/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solar.edge.app;

import org.junit.jupiter.api.Test;

import com.solar.edge.Library;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
